=== nuvla/etsi-mec-robot-test-suite/MEC010p2/MEPM/PKGM/schemas/AppPkgNotification.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "notificationType": {
      "type": "string"
    },
    "subscriptionId": {
      "type": "string"
    },
    "timeStamp": {
      "type": "object",
      "properties": {
        "seconds": {
          "type": "integer"
        },
        "nanoSeconds": {
          "type": "integer"
        }
      },
      "required": [
        "seconds",
        "nanoSeconds"
      ]
    },
    "appPkgId": {
      "type": "string"
    },
    "appDId": {
      "type": "string"
    },
    "operationalState": {
      "type": "string"
    },
    "_links": {
      "type": "object",
      "properties": {
        "subscription": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [
            "href"
          ]
        }
      },
      "required": [
        "subscription"
      ]
    }
  },
  "required": [
    "id",
    "notificationType",
    "subscriptionId",
    "timeStamp",
    "appPkgId",
    "appDId",
    "operationalState",
    "_links"
  ]
}

=== nuvla/etsi-mec-robot-test-suite/MEC010p2/MEO/PKGM/jsons/AppPkgNotification.json
{
    "id": "1234",
    "notificationType": "AppPackageOnBoarded",
    "subscriptionId": "1234",
    "timeStamp": {
        "seconds": 1234,
        "nanoSeconds": 1234
    },
    "appPkgId": "appPkgId",
    "appDId": "appDId",
    "operationalState": "ENABLED",
    "_links": {
        "subscription": {
            "href": "someuri/url"
        }
    }
}
